Models/ErrorViewModel.cs
namespace McvCoreUtilidades.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CachingController.cs
using System.Runtime.InteropServices.JavaScript;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace McvCoreUtilidades.Controllers;

public class CachingController : Controller
{
    private IMemoryCache _memoryCache;
    public CachingController(IMemoryCache memoryCache)
    {
        _memoryCache = memoryCache;
    }
    // GET
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult MemoriaPersonalizada(int? tiempo)
    {
        if (tiempo == null)
        {
            tiempo = 60;
        }
        string fecha = DateTime.Now.ToLongDateString() + " -- " +
                       DateTime.Now.ToLongTimeString();
        
        //COMO ESTO ES MANUAL, DEBEMOS PREGUNTAR SI EXISTE
        //ALGO EN CACHE O NO

        if (_memoryCache.Get("FECHA") == null)
        {
            //NO EXISTE CACHE TODAVIA
            //CREAMOS EL OBJETO ENTRY OPTIONS CON EL TIEMPO
            MemoryCacheEntryOptions options =
                new MemoryCacheEntryOptions().SetAbsoluteExpiration(TimeSpan.FromSeconds(tiempo.Value));
            
            _memoryCache.Set("FECHA", fecha,options);
            ViewData["MENSAJE"] = "Fecha almacenada correctamente";
            ViewData["FECHA"] = _memoryCache.Get("FECHA");
        }
        else
        {
            //EXISTE CACHE Y LO RECUPERAMOS
            fecha = _memoryCache.Get<string>("FECHA");
            ViewData["MENSAJE"] = "Fecha recuperada correctamente";
            ViewData["FECHA"] = fecha;
        }
        return View();
    }

    [ResponseCache(Duration=60,
        Location = ResponseCacheLocation.Client)]
    public IActionResult MemoriaDistribuida()
    {
        string fecha = DateTime.Now.ToLongDateString() + " -- " +
                       DateTime.Now.ToLongTimeString();
        ViewData["FECHA"] = fecha;
        return View();
    }
}

Controllers/CifradosController.cs
using Microsoft.AspNetCore.Mvc;

namespace McvCoreUtilidades.Controllers;

public class CifradosController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using McvCoreUtilidades.Models;
using Microsoft.AspNetCore.Mvc;

namespace McvCoreUtilidades.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UploadFilesController.cs
using McvCoreUtilidades.Helpers;
using Microsoft.AspNetCore.Mvc;

namespace McvCoreUtilidades.Controllers;

public class UploadFilesController : Controller
{

    private HelperPathProvider _helperPath;
    
    public UploadFilesController(HelperPathProvider helperPath)
    {
        _helperPath = helperPath;
    }
    public IActionResult SubirFile()
    {
        return View();
    }   
    [HttpPost]
    public async Task<IActionResult> SubirFile(IFormFile fichero)
    {
 
        string fileName = fichero.FileName;

        string path = _helperPath.MapPath(fileName, Folders.Productos);
        
        //PARA SUBIR FICHEROS UTLIZAMOS Stream
        using (Stream stream = new FileStream(path, FileMode.Create))
        {
            await fichero.CopyToAsync(stream);
        }

        ViewData["MENSAJE"] = "Fichero subido a " + path;

        ViewData["PATH"] = _helperPath.MapUrlPath(fileName,Folders.Productos);
        
        return View();
    }
    
    
}

Views/Caching/Index.cshtml
<h1>Memoria Caching</h1>


<ul class="list-group">
    <li class="list-group-item">
        <a asp-controller="Caching"
           asp-action="MemoriaDistribuida">
            Actualizar Distribuido
        </a>
    </li>
    <li class="list-group-item">
        <a asp-controller="Caching"
           asp-action="MemoriaPersonalizada">
            Memoria Personalizada
        </a>
        
    </li>
</ul>

Views/Caching/MemoriaDistribuida.cshtml
<h1>Memoria Distribuida</h1>


<p>
    <a asp-controller="Caching"
       asp-action="MemoriaDistribuida">
        Actualizar página
    </a>
</p>


<h2 class="text-danger">@ViewData["FECHA"]</h2>

Views/Caching/MemoriaPersonalizada.cshtml
<h1>Memoria Personalizada</h1>


<p>
    <a asp-controller="Caching"
       asp-action="MemoriaPersonalizada">
        Actualizar página
    </a>
</p>
<p>
    <a asp-controller="Caching"
       asp-action="MemoriaPersonalizada"
       asp-route-tiempo="15">
        Actualizar página 15 segundos
    </a>
</p>
<p>
    <a asp-controller="Caching"
       asp-action="MemoriaPersonalizada"
       asp-route-tiempo="30">
        Actualizar página 30 segundos
    </a>
</p>


<h2 class="text-primary">@ViewData["MENSAJE"]</h2>
<h2 class="text-danger">@ViewData["FECHA"]</h2>

Views/Cifrados/Index.cshtml
@model TModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
<div>
      
</div>
</body>
</html>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - McvCoreUtilidades</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/McvCoreUtilidades.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">McvCoreUtilidades</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" 
                               asp-controller="UploadFiles"
                               asp-action="SubirFile">Subir Files</a>
                        </li>   
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" 
                               asp-controller="Caching"
                               asp-action="Index">Caching</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - McvCoreUtilidades - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/UploadFiles/SubirFile.cshtml
<h1>Subir ficheros Net Core</h1>

<form method="post" enctype="multipart/form-data">
    <label>Seleccione un fichero:</label>
    <input type="file" name="fichero" class="form-control"/>
    <button class="btn btn-info">
        Subir Fichero
    </button>
</form>

<h2 style="color: blue">
    @ViewData["MENSAJE"]
</h2>
<img src='@ViewData["PATH"]'/>

<h3 style="color: red">
    @ViewData["PATH"]
</h3>